In [1]:
# coding:utf-8
import numpy as np
from matplotlib import pyplot as plt

In [5]:
# 索引
n1 = np.random.randint(0, 100, (5, 7))
n1

array([[41, 66, 72, 96, 14, 78, 73],
       [71, 16, 95, 32,  2, 73, 11],
       [14, 84, 18, 81, 52, 56, 37],
       [46, 78, 50, 86, 74, 10, 66],
       [21, 23, 83, 95, 45, 33, 43]])

In [7]:
print(n1[1][2], n1[2, 3])

95 81


In [8]:
# 切片
n2 = np.random.randint(150, size=10)
n2

array([ 49, 127, 130, 144,  99, 146,   7,  33,  56, 143])

In [13]:
# 对多维数组切片时，每一维使用逗号分隔
n1[1:3, :4]

array([[71, 16, 95, 32],
       [14, 84, 18, 81]])

In [15]:
# 将数组反向输出
# 一个“:”代表切片，两个“::”代表取数字，-1表示从后往前取数字
# -1是间隔
n3 = np.arange(0, 10, 1)
n3[::-2]

array([9, 7, 5, 3, 1])

In [16]:
# reshape变形
n3.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
# reshape中参数如果是负数，则直接将数组转化成一维数组
n3.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])