In [21]:
# coding:utf-8
import numpy as np
# fft是傅里叶转换，ifft是傅里叶反转
from numpy.fft import fft, ifft
from PIL import Image

In [30]:
# 根据物体边界的变化程度来提取物体轮廓，使用傅里叶变换
path = r'E:\python\PythonSpace\Git\Python\DataAnalysis\Data\dog.jpg'
dog = Image.open(path)
dog.show()

In [22]:
# 将dog转化成int类型的数据，超出当前数据范围的数字就变成负数
dog_data = np.fromstring(dog.tobytes(), dtype=np.int8)
dog_data

array([-113, -116, -121, ...,  124,  123,  118], dtype=int8)

In [23]:
# 傅里叶转换，转换结果是虚数
dog_fft = fft(dog_data)
# 将真实数据转化成频域
dog_fft

array([ 23856095.00000000       +0.j        ,
        -3624006.87370139+11148439.03089775j,
        -4196914.91332539+13008279.04788709j, ...,
         3678377.62589230  -985606.13142507j,
        -4196914.91332550-13008279.04788707j,
        -3624006.87370148-11148439.03089774j])

In [31]:
# 滤波，将傅里叶变换结果中低频(<10万)数据设置成0
# dog_fft[np.where(np.abs(dog_fft)<1e5)] = 0
np.where(np.abs(dog_fft)<1e7, 0, dog_fft)

array([ 23856095.00000000       +0.j        ,
        -3624006.87370139+11148439.03089775j,
        -4196914.91332539+13008279.04788709j, ...,
               0.00000000       +0.j        ,
        -4196914.91332550-13008279.04788707j,
        -3624006.87370148-11148439.03089774j])

In [32]:
# 数据反转
dog_ifft = ifft(dog_fft)
dog_ifft

array([-113. +2.85242923e-12j, -116. +1.75796739e-13j,
       -121. +3.32959044e-13j, ...,  124. -7.62530299e-13j,
        123. -9.42104019e-13j,  118. -1.07803076e-12j])

In [26]:
# 只要实数部分
dog_real = np.real(dog_ifft)
dog_real

array([-113., -116., -121., ...,  124.,  123.,  118.])

In [33]:
# 去除小数部分
dog_result = np.int8(dog_real)
dog_result

array([-112, -115, -120, ...,  123,  123,  118], dtype=int8)

In [34]:
# 将数组转成图片
dog_Image = Image.frombytes(size=dog.size, mode=dog.mode, data=dog_result)
dog_Image.show()