In [1]:
# coding:utf-8
import numpy as np

In [2]:
n1 = np.ones((2, 3))
n2 = np.arange(3)
print(n1)
print(n2)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[0 1 2]


In [11]:
# n1和n2的维度不相同，但是在numpy中可以直接做加法
# 因为numpy中存在广播机制，维度不对应时，自动补全
# 比如就将n2补成了[[1,2,3],[1,2,3]]，它使用原本数组中
# 存在的内容补充其它，这个自动补全必须保证列数是相同的
# n3 = n1 * n2，将n1和n2的对应位置相乘
n2 = np.random.randint(0, 10, size=3)
n3 = n1.dot(n2)
print(n2)
print(n3)

[8 5 1]
[ 14.  14.]


In [12]:
# 排序
n1 = np.array([2, 9, 4, 7, 3])
# 快排，可以传axis参数，对行列进行排序
# np.sort(n1)
n1.sort()
n1

array([2, 3, 4, 7, 9])

In [13]:
# np.sort()可以选择快排、堆排序和归并排序
np.sort(n1)
n1

array([2, 3, 4, 7, 9])

In [15]:
# 部分排序
n4 = np.random.randint(0, 150, size=30)
n4

array([118,  33,   3,  50,  55,  94, 125,  62,  12,  88,  29, 132,  25,
        71, 101,  23,  91,  62,  71,   1, 108, 128, 124, 100,  87,  59,
       116,  87,  20,  82])

In [17]:
# 5表示将整个数组中的最小的5个数放在数组头部
# -5表示将整个数组中的最大的5个数放在数组末尾
np.partition(n4, 5)

array([ 12,   1,   3,  20,  23,  25,  29,  33,  55,  50,  59,  62,  71,
        71,  82,  62,  87,  91,  87,  88,  94, 100, 101, 124, 128, 108,
       116, 132, 125, 118])