In [1]:
# coding:utf-8
import numpy as np

In [3]:
n1 = np.random.randint(0, 10, size=(4, 5))
n1

array([[6, 2, 2, 7, 9],
       [0, 3, 5, 8, 5],
       [1, 4, 3, 3, 7],
       [1, 0, 2, 0, 7]])

In [4]:
# 级联， 默认axis=0，从行上进行级联
# 当axis=1时，则从列上进行级联
np.concatenate((n1, n1))

array([[6, 2, 2, 7, 9],
       [0, 3, 5, 8, 5],
       [1, 4, 3, 3, 7],
       [1, 0, 2, 0, 7],
       [6, 2, 2, 7, 9],
       [0, 3, 5, 8, 5],
       [1, 4, 3, 3, 7],
       [1, 0, 2, 0, 7]])

In [6]:
n2 = np.arange(0, 10, 2)
n2

array([0, 2, 4, 6, 8])

In [7]:
# 将水平的数组转化成竖直的数组，相当于升一个维度
n3 = np.vstack(n2)
n3

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
# 将竖直数组转化成水平数组，相当于降一个维度
n4 = np.array([[2, 3, 4, 5, 6]])
np.hstack(n4)

array([2, 3, 4, 5, 6])

In [10]:
# 切分
n5 = np.random.randint(0, 150, size=(4, 5))
n5

array([[ 31,  20,   0, 126,  86],
       [112,  97, 102,  83, 130],
       [ 20,  83,  95,  82,  52],
       [ 92,  76, 136,  49,  68]])

In [12]:
# 对数组进行切分，将0、1、2-3行分别切分成一个数组
# 默认axis=0，从行进行切分，当axis=1时，则从列进行切分
# 也可以使用vsplit和 hsplit，从行、列切分数组
np.split(n5, (1, 2))

[array([[ 31,  20,   0, 126,  86]]),
 array([[112,  97, 102,  83, 130]]),
 array([[ 20,  83,  95,  82,  52],
        [ 92,  76, 136,  49,  68]])]

In [15]:
from matplotlib import pyplot as plt
image = plt.imread(r'E:\python\PythonSpace\Git\Python\DataAnalysis\Data\Numpy\14.jpg')
image2 = np.split(image, (100, 900))[1]
plt.imshow(image2)
plt.show()