In [2]:
# coding:utf-8
import numpy as np
from matplotlib import pyplot as plt

In [3]:
path = r'E:\python\PythonSpace\Git\Python\DataAnalysis\Data\Numpy\14.jpg'
image = plt.imread(path)
image.max()

255

In [6]:
# 当不写axis时，求的是整个数组中的最大值
# 当axis=0时，则求每一行的最大值
# 当axis=1时，则求每一列的最大值
# axis还可以等于2，求的就是每个二维向量中的最大值
image.max(axis=2)

array([[233, 233, 233, ..., 204, 205, 205],
       [234, 234, 234, ..., 204, 204, 204],
       [234, 234, 234, ..., 204, 204, 204],
       ..., 
       [154, 155, 156, ..., 247, 248, 248],
       [158, 159, 161, ..., 249, 249, 249],
       [160, 160, 162, ..., 249, 249, 249]], dtype=uint8)

In [9]:
image.mean(axis=1)

array([[ 224.7375    ,  207.30833333,  172.03541667],
       [ 224.86822917,  207.4390625 ,  172.16614583],
       [ 225.040625  ,  207.61979167,  172.33020833],
       ..., 
       [ 213.00625   ,  186.47916667,  157.06302083],
       [ 213.69479167,  187.3109375 ,  157.79895833],
       [ 214.50052083,  188.125     ,  158.70625   ]])

In [12]:
image.sum(axis=0)

array([[206467, 178066, 144161],
       [208964, 180953, 146323],
       [210956, 183066, 147521],
       ..., 
       [259415, 250506, 217651],
       [259478, 250476, 217658],
       [259463, 250579, 217622]], dtype=uint32)

In [15]:
image.argmax()

2403204

In [17]:
n1 = np.random.randint(0, 100, size=10)
n1

array([43, 32, 15, 26, 82, 53, 88, 68, 22, 73])

In [18]:
# 返回最大值的索引
n1.argmax() 

6

In [19]:
# 找到大于30的数字的索引
np.argwhere(n1>30)

array([[0],
       [1],
       [4],
       [5],
       [6],
       [7],
       [9]], dtype=int64)